initial-health-multiplier: 1.0
health-multiplier: 1.02
mitosis: 2
unit-bind: false

block-whitelist:
  - shock-mine

drops:
  serpulo-tier1-drop:
    - item: "copper"
      amount: 25
    - item: "lead"
      amount: 25
    - item: "silicon"
      amount: 10
    - type: "random"
      items:
        - item: "graphite"
          amount: 20
        - item: "metaglass"
          amount: 15
        - item: "titanium"
          amount: 15

  serpulo-tier2-drop:
    - item: "copper"
      amount: 40
    - item: "lead"
      amount: 40
    - item: "silicon"
      amount: 20
    - item: "graphite"
      amount: 20
    - type: "random"
      items:
        - item: "graphite"
          amount: 20
        - item: "metaglass"
          amount: 35
        - item: "titanium"
          amount: 25

  serpulo-tier3-drop:
    - item: "copper"
      amount: 60
    - item: "lead"
      amount: 60
    - item: "silicon"
      amount: 30
    - item: "graphite"
      amount: 30
    - item: "titanium"
      amount: 20
    - item: "thorium"
      amount: 10
    - item: "plastanium"
      amount: 30
    - type: "random"
      items:
        - item: "graphite"
          amount: 30
        - item: "metaglass"
          amount: 20
        - item: "titanium"
          amount: 30
        - item: "surge-alloy"
          amount: 10
        - item: "phase-fabric"
          amount: 20

  serpulo-tier4-drop:
    - item: "copper"
      amount: 200
    - item: "lead"
      amount: 200
    - item: "silicon"
      amount: 50
    - item: "titanium"
      amount: 100
    - item: "thorium"
      amount: 40
    - item: "phase-fabric"
      amount: 30
    - item: "surge-alloy"
      amount: 30
    - type: "random"
      items:
        - item: "graphite"
          amount: 30
        - item: "metaglass"
          amount: 30
        - item: "titanium"
          amount: 30
        - item: "plastanium"
          amount: 80
        - item: "thorium"
          amount: 80

  serpulo-tier5-drop:
    - item: "copper"
      amount: 300
    - item: "lead"
      amount: 300
    - item: "silicon"
      amount: 100
    - item: "thorium"
      amount: 60
    - item: "phase-fabric"
      amount: 40
    - item: "surge-alloy"
      amount: 60
    - type: "random"
      items:
        - item: "graphite"
          amount: 40
        - item: "metaglass"
          amount: 40
        - item: "titanium"
          amount: 40
        - item: "plastanium"
          amount: 120
        - item: "thorium"
          amount: 120

  erekir-tier1-drop:
    - item: "beryllium"
      amount: 30
    - item: "graphite"
      amount: 10
    - item: "silicon"
      amount: 15
    - type: "random"
      items:
        - item: "beryllium"
          amount: 15
        - item: "graphite"
          amount: 10
        - item: "tungsten"
          amount: 5
        - item: "oxide"
          amount: 10

  erekir-tier2-drop:
    - item: "beryllium"
      amount: 55
    - item: "graphite"
      amount: 25
    - item: "silicon"
      amount: 25
    - item: "tungsten"
      amount: 20
    - type: "random"
      items:
        - item: "beryllium"
          amount: 30
        - item: "tungsten"
          amount: 15
        - item: "oxide"
          amount: 20

  erekir-tier3-drop:
    - item: "beryllium"
      amount: 80
    - item: "graphite"
      amount: 40
    - item: "silicon"
      amount: 35
    - item: "tungsten"
      amount: 60
    - item: "oxide"
      amount: 50
    - item: "thorium"
      amount: 15
    - type: "random"
      items:
        - item: "beryllium"
          amount: 50
        - item: "tungsten"
          amount: 25
        - item: "thorium"
          amount: 35
        - item: "surge-alloy"
          amount: 55
        - item: "carbide"
          amount: 50

  erekir-tier4-drop:
    - item: "beryllium"
      amount: 250
    - item: "graphite"
      amount: 150
    - item: "silicon"
      amount: 250
    - item: "tungsten"
      amount: 100
    - item: "oxide"
      amount: 60
    - item: "thorium"
      amount: 80
    - item: "surge-alloy"
      amount: 50
    - item: "carbide"
      amount: 50
    - type: "random"
      items:
        - item: "thorium"
          amount: 30
        - item: "tungsten"
          amount: 60
        - item: "carbide"
          amount: 30
        - item: "surge-alloy"
          amount: 80
        - item: "phase-fabric"
          amount: 80

  erekir-tier5-drop:
    - item: "beryllium"
      amount: 400
    - item: "graphite"
      amount: 300
    - item: "silicon"
      amount: 250
    - item: "tungsten"
      amount: 100
    - item: "thorium"
      amount: 80
    - item: "oxide"
      amount: 150
    - item: "surge-alloy"
      amount: 60
    - item: "carbide"
      amount: 80
    - item: "phase-fabric"
      amount: 50
    - type: "random"
      items:
        - item: "oxide"
          amount: 80
        - item: "surge-alloy"
          amount: 50
        - item: "carbide"
          amount: 60
        - item: "phase-fabric"
          amount: 120
        - item: "thorium"
          amount: 160

units:
  # Serpulo Tree
  # Dagger Tree
  dagger:
    drop: "serpulo-tier1-drop"
  mace:
    drop: "serpulo-tier2-drop"
    downgrade: "dagger"
  fortress:
    drop: "serpulo-tier3-drop"
    downgrade: "mace"
  scepter:
    drop: "serpulo-tier4-drop"
    downgrade: "fortress"
  reign:
    drop: "serpulo-tier5-drop"
    downgrade: "scepter"

  # Crawler Tree
  crawler:
    drop: "serpulo-tier1-drop"
  atrax:
    drop: "serpulo-tier2-drop"
    downgrade: "crawler"
  spiroct:
    drop: "serpulo-tier3-drop"
    downgrade: "atrax"
  arkyid:
    drop: "serpulo-tier4-drop"
    downgrade: "spiroct"
  toxopid:
    drop: "serpulo-tier5-drop"
    downgrade: "arkyid"

  # Nova Tree
  nova:
    drop: "serpulo-tier1-drop"
  pulsar:
    drop: "serpulo-tier2-drop"
    downgrade: "nova"
  quasar:
    drop: "serpulo-tier3-drop"
    downgrade: "pulsar"
  vela:
    drop: "serpulo-tier4-drop"
    downgrade: "quasar"
  corvus:
    drop: "serpulo-tier5-drop"
    downgrade: "vela"

  # Mono Tree
  mono:
    drop: "serpulo-tier1-drop"
  poly:
    drop: "serpulo-tier2-drop"
    downgrade: "mono"
  mega:
    drop: "serpulo-tier3-drop"
    downgrade: "poly"
  quad:
    drop: "serpulo-tier4-drop"
    downgrade: "mega"
  oct:
    drop: "serpulo-tier5-drop"
    downgrade: "quad"

  # Flare Tree
  flare:
    drop: "serpulo-tier1-drop"
  horizon:
    drop: "serpulo-tier2-drop"
    downgrade: "flare"
  zenith:
    drop: "serpulo-tier3-drop"
    downgrade: "horizon"
  antumbra:
    drop: "serpulo-tier4-drop"
    downgrade: "zenith"
  eclipse:
    drop: "serpulo-tier5-drop"
    downgrade: "antumbra"

  # Risso Tree - Naval
  risso:
    drop: "serpulo-tier1-drop"
  minke:
    drop: "serpulo-tier2-drop"
    downgrade: "risso"
  bryde:
    drop: "serpulo-tier3-drop"
    downgrade: "minke"
  sei:
    drop: "serpulo-tier4-drop"
    downgrade: "bryde"
  omura:
    drop: "serpulo-tier5-drop"
    downgrade: "sei"

  # Retusa Tree - Naval
  retusa:
    drop: "serpulo-tier1-drop"
  oxynoe:
    drop: "serpulo-tier2-drop"
    downgrade: "retusa"
  cyerce:
    drop: "serpulo-tier3-drop"
    downgrade: "oxynoe"
  aegires:
    drop: "serpulo-tier4-drop"
    downgrade: "cyerce"
  navanax:
    drop: "serpulo-tier5-drop"
    downgrade: "cyerce"

  # Erekir Tree
  # Stell Tree
  stell:
    drop: "erekir-tier1-drop"
  locus:
    drop: "erekir-tier2-drop"
    downgrade: "stell"
  precept:
    drop: "erekir-tier3-drop"
    downgrade: "locus"
  vanquish:
    drop: "erekir-tier4-drop"
    downgrade: "precept"
  conquer:
    drop: "erekir-tier5-drop"
    downgrade: "vanquish"

  # Elude Tree
  elude:
    drop: "erekir-tier1-drop"
  avert:
    drop: "erekir-tier2-drop"
    downgrade: "elude"
  obviate:
    drop: "erekir-tier3-drop"
    downgrade: "avert"
  quell:
    drop: "erekir-tier4-drop"
    downgrade: "obviate"
  disrupt:
    drop: "erekir-tier5-drop"
    downgrade: "quell"

  # Merui Tree
  merui:
    drop: "erekir-tier1-drop"
  cleroi:
    drop: "erekir-tier2-drop"
    downgrade: "merui"
  anthicus:
    drop: "erekir-tier3-drop"
    downgrade: "cleroi"
  tecta:
    drop: "erekir-tier4-drop"
    downgrade: "anthicus"
  collaris:
    drop: "erekir-tier5-drop"
    downgrade: "tecta"

  # Erekir Core Unit
  evoke:
    drop: "erekir-tier2-drop"
  incite:
    drop: "erekir-tier3-drop"
    downgrade: "evoke"
  emanate:
    drop: "erekir-tier4-drop"
    downgrade: "incite"

  # Serpulo Core Unit
  alpha:
    drop: "serpulo-tier1-drop"
  beta:
    drop: "serpulo-tier2-drop"
    downgrade: "alpha"
  gamma:
    drop: "serpulo-tier3-drop"
    downgrade: "beta"

  # Latum Tree - TODO: Remove in v9?
  renale:
    drop: "erekir-tier2-drop"
  latum:
    drop: "erekir-tier5-drop"
    downgrade: "renale"
