[versions]
# plugins
shadow = "9.2.2"
indra = "3.2.0"
toxopid = "4.1.2"
spotless = "8.0.0"
errorprone-gradle = "4.3.0"

# utilities
slf4md = "1.1.1"
distributor = "4.2.0"
snakeyaml = "2.5"
gestalt = "0.36.0"

# static analysis
errorprone-core = "2.42.0"
nullaway = "0.12.10"
jspecify = "1.0.0"

[libraries]
# utilities
distributor-api = { module = "com.xpdustry:distributor-common-api", version.ref = "distributor" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
gestalt-core = { module = "com.github.gestalt-config:gestalt-core", version.ref = "gestalt" }

# static analysis
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-core" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[plugins]
indra-common = { id = "net.kyori.indra", version.ref = "indra" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
toxopid = { id = "com.xpdustry.toxopid", version.ref = "toxopid" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
errorprone-gradle = { id = "net.ltgt.errorprone", version.ref = "errorprone-gradle" }
